spring:
  application:
    name: bargain-ms
    group: by.zemich.trading-bot

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

binance:
  API_KEY: ${API_KEY:key}
  SECRET_KEY: ${SECRET_KEY:secret}

strategies:
  simple-spot-strategies:
    enabled: true
    trade-amount: 10
    percentage-interest: 1.2

